[server]
headless = true
maxUploadSize = 30

[client]
toolbarMode = "minimal"

[theme]
base = "light"
primaryColor = "#E8490F"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F7F5F2"
textColor = "#333333"
